### ISSUE TITLE
Fix Inference

### ISSUE THREAD

**Issue by ethanleifer** [jxnl/instructor-js#54]
Type `z.infer<typeof UserSchema> | never` should be inferred through by the return type

I am pretty sure this comes from the helper `makeCompletionCall` in `chatCompletion` returning `Promise<any>`

<img width="584" alt="Screenshot 2024-01-05 at 9 14 19 PM" src="https://github.com/jxnl/instructor-js/assets/17654498/908c01cd-4dfe-4635-b973-325900420483">

**Comment by abeisleem** [comment]
I think this is broken again. Using v1.5.0 w/ Deno

![image](https://github.com/user-attachments/assets/41ae2f6e-e044-4c68-8bfb-503aa70d46c2)
